export const intakeOutputMockData = [
    {
        "encounterDateTime": 1709751755000,
        "visitStartDateTime": 1709291229000,
        "targetObsRelation": null,
        "groupMembers": [
            {
                "encounterDateTime": 1709751755000,
                "visitStartDateTime": 1709291229000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Coded",
                "encounterUuid": "ace83e56-e4a2-4418-a337-0a837ab026c6",
                "obsGroupUuid": "c26483b0-98ff-4030-8484-55dcb6176370",
                "creatorName": "Super Man",
                "conceptSortWeight": 2,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-0/7-0/8-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1709751819000,
                "conceptNameToDisplay": "Output Route",
                "valueAsString": "Urine",
                "concept": {
                    "uuid": "c6e830c6-2104-8068-3dcd-fd6ad833a5ac",
                    "name": "Output Route",
                    "dataType": "Coded",
                    "shortName": "Output Route",
                    "units": null,
                    "conceptClass": "Question",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "conceptUuid": "c6e830c6-2104-8068-3dcd-fd6ad833a5ac",
                "voidReason": null,
                "uuid": "f8982c17-9f8c-4c5f-bf0e-44a6ab5b845c",
                "voided": false,
                "comment": "output route notes",
                "value": {
                    "uuid": "6c204711-527c-2727-9002-5ff260a16881",
                    "name": "Output Route Urine",
                    "dataType": "N/A",
                    "shortName": "Urine",
                    "units": null,
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                }
            },
            {
                "encounterDateTime": 1709751755000,
                "visitStartDateTime": 1709291229000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Numeric",
                "encounterUuid": "ace83e56-e4a2-4418-a337-0a837ab026c6",
                "obsGroupUuid": "c26483b0-98ff-4030-8484-55dcb6176370",
                "creatorName": "Super Man",
                "conceptSortWeight": 3,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-0/7-0/9-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1709751819000,
                "conceptNameToDisplay": "Output Quantity",
                "valueAsString": "100.0",
                "concept": {
                    "uuid": "0656118f-8c8e-3bd9-6554-619e5c678a4b",
                    "name": "Output Quantity",
                    "dataType": "Numeric",
                    "shortName": "Output Quantity",
                    "units": "ml",
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "conceptUuid": "0656118f-8c8e-3bd9-6554-619e5c678a4b",
                "voidReason": null,
                "uuid": "937b1a5d-ec4b-42c0-b5c3-737732080c28",
                "voided": false,
                "comment": "output quantity notes",
                "value": 100.0
            },
            {
                "encounterDateTime": 1709751755000,
                "visitStartDateTime": 1709291229000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Datetime",
                "encounterUuid": "ace83e56-e4a2-4418-a337-0a837ab026c6",
                "obsGroupUuid": "c26483b0-98ff-4030-8484-55dcb6176370",
                "creatorName": "Super Man",
                "conceptSortWeight": 4,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-0/7-0/10-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1709751819000,
                "conceptNameToDisplay": "Date & Time",
                "valueAsString": "2024-03-07 11:00:00",
                "concept": {
                    "uuid": "8a81f755-4993-25f0-3490-963787e98dbf",
                    "name": "Output Date & Time",
                    "dataType": "Datetime",
                    "shortName": "Date & Time",
                    "units": null,
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "conceptUuid": "8a81f755-4993-25f0-3490-963787e98dbf",
                "voidReason": null,
                "uuid": "c9033959-9f14-421d-9e70-384925c69f01",
                "voided": false,
                "comment": null,
                "value": "2024-03-07 11:00:00"
            }
        ],
        "providers": [
            {
                "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                "name": "Super Man",
                "encounterRoleUuid": null
            }
        ],
        "isAbnormal": null,
        "duration": null,
        "type": null,
        "encounterUuid": "ace83e56-e4a2-4418-a337-0a837ab026c6",
        "obsGroupUuid": null,
        "creatorName": "Super Man",
        "conceptSortWeight": 5,
        "parentConceptUuid": null,
        "hiNormal": null,
        "lowNormal": null,
        "formNamespace": "Bahmni",
        "formFieldPath": "Intake & Output.1/11-0/7-0",
        "interpretation": null,
        "status": "FINAL",
        "encounterTypeName": "Consultation",
        "complexData": null,
        "abnormal": null,
        "unknown": false,
        "orderUuid": null,
        "observationDateTime": 1709751819000,
        "conceptNameToDisplay": "Output",
        "valueAsString": "March 7, 2024 11:00:00 AM IST, 100.0, Output Route Urine",
        "concept": {
            "uuid": "c090ae63-6b65-4958-9c74-77e3bf118206",
            "name": "Output Section",
            "dataType": "N/A",
            "shortName": "Output",
            "units": null,
            "conceptClass": "ConvSet",
            "hiNormal": null,
            "lowNormal": null,
            "set": true,
            "mappings": []
        },
        "conceptUuid": "c090ae63-6b65-4958-9c74-77e3bf118206",
        "voidReason": null,
        "uuid": "c26483b0-98ff-4030-8484-55dcb6176370",
        "voided": false,
        "comment": null,
        "value": "March 7, 2024 11:00:00 AM IST, 100.0, Output Route Urine"
    },
    {
        "encounterDateTime": 1709751755000,
        "visitStartDateTime": 1709291229000,
        "targetObsRelation": null,
        "groupMembers": [
            {
                "encounterDateTime": 1709751755000,
                "visitStartDateTime": 1709291229000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Coded",
                "encounterUuid": "ace83e56-e4a2-4418-a337-0a837ab026c6",
                "obsGroupUuid": "81adb56a-b5f8-42e7-b21e-fce36e21d50a",
                "creatorName": "Super Man",
                "conceptSortWeight": 2,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-1/7-0/8-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1709751819000,
                "conceptNameToDisplay": "Output Route",
                "valueAsString": "Vomit",
                "concept": {
                    "uuid": "c6e830c6-2104-8068-3dcd-fd6ad833a5ac",
                    "name": "Output Route",
                    "dataType": "Coded",
                    "shortName": "Output Route",
                    "units": null,
                    "conceptClass": "Question",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "conceptUuid": "c6e830c6-2104-8068-3dcd-fd6ad833a5ac",
                "voidReason": null,
                "uuid": "bd1a3486-d9b3-45f6-8b05-ff4ef3121511",
                "voided": false,
                "comment": null,
                "value": {
                    "uuid": "e45839b8-0dcd-5085-3d2d-3673e56b9eb4",
                    "name": "Output Route Vomit",
                    "dataType": "N/A",
                    "shortName": "Vomit",
                    "units": null,
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                }
            },
            {
                "encounterDateTime": 1709751755000,
                "visitStartDateTime": 1709291229000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Numeric",
                "encounterUuid": "ace83e56-e4a2-4418-a337-0a837ab026c6",
                "obsGroupUuid": "81adb56a-b5f8-42e7-b21e-fce36e21d50a",
                "creatorName": "Super Man",
                "conceptSortWeight": 3,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-1/7-0/9-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1709751819000,
                "conceptNameToDisplay": "Output Quantity",
                "valueAsString": "200.0",
                "concept": {
                    "uuid": "0656118f-8c8e-3bd9-6554-619e5c678a4b",
                    "name": "Output Quantity",
                    "dataType": "Numeric",
                    "shortName": "Output Quantity",
                    "units": "ml",
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "conceptUuid": "0656118f-8c8e-3bd9-6554-619e5c678a4b",
                "voidReason": null,
                "uuid": "f884fc63-d048-4c9b-b5c6-6c657dafa21d",
                "voided": false,
                "comment": null,
                "value": 200.0
            },
            {
                "encounterDateTime": 1709751755000,
                "visitStartDateTime": 1709291229000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Datetime",
                "encounterUuid": "ace83e56-e4a2-4418-a337-0a837ab026c6",
                "obsGroupUuid": "81adb56a-b5f8-42e7-b21e-fce36e21d50a",
                "creatorName": "Super Man",
                "conceptSortWeight": 4,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-1/7-0/10-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1709751819000,
                "conceptNameToDisplay": "Date & Time",
                "valueAsString": "2024-03-07 13:00:00",
                "concept": {
                    "uuid": "8a81f755-4993-25f0-3490-963787e98dbf",
                    "name": "Output Date & Time",
                    "dataType": "Datetime",
                    "shortName": "Date & Time",
                    "units": null,
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "conceptUuid": "8a81f755-4993-25f0-3490-963787e98dbf",
                "voidReason": null,
                "uuid": "3c8817dd-afd1-421d-a6e8-3b09fab7a3e1",
                "voided": false,
                "comment": null,
                "value": "2024-03-07 13:00:00"
            }
        ],
        "providers": [
            {
                "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                "name": "Super Man",
                "encounterRoleUuid": null
            }
        ],
        "isAbnormal": null,
        "duration": null,
        "type": null,
        "encounterUuid": "ace83e56-e4a2-4418-a337-0a837ab026c6",
        "obsGroupUuid": null,
        "creatorName": "Super Man",
        "conceptSortWeight": 5,
        "parentConceptUuid": null,
        "hiNormal": null,
        "lowNormal": null,
        "formNamespace": "Bahmni",
        "formFieldPath": "Intake & Output.1/11-1/7-0",
        "interpretation": null,
        "status": "FINAL",
        "encounterTypeName": "Consultation",
        "complexData": null,
        "abnormal": null,
        "unknown": false,
        "orderUuid": null,
        "observationDateTime": 1709751819000,
        "conceptNameToDisplay": "Output",
        "valueAsString": "Output Route Vomit, March 7, 2024 1:00:00 PM IST, 200.0",
        "concept": {
            "uuid": "c090ae63-6b65-4958-9c74-77e3bf118206",
            "name": "Output Section",
            "dataType": "N/A",
            "shortName": "Output",
            "units": null,
            "conceptClass": "ConvSet",
            "hiNormal": null,
            "lowNormal": null,
            "set": true,
            "mappings": []
        },
        "conceptUuid": "c090ae63-6b65-4958-9c74-77e3bf118206",
        "voidReason": null,
        "uuid": "81adb56a-b5f8-42e7-b21e-fce36e21d50a",
        "voided": false,
        "comment": null,
        "value": "Output Route Vomit, March 7, 2024 1:00:00 PM IST, 200.0"
    },
    {
        "encounterDateTime": 1709751755000,
        "visitStartDateTime": 1709291229000,
        "targetObsRelation": null,
        "groupMembers": [
            {
                "encounterDateTime": 1709751755000,
                "visitStartDateTime": 1709291229000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Coded",
                "encounterUuid": "ace83e56-e4a2-4418-a337-0a837ab026c6",
                "obsGroupUuid": "e58c4f98-8c5c-4dc9-8be1-780cedf9f701",
                "creatorName": "Super Man",
                "conceptSortWeight": 2,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-0/3-0/4-0",
                "interpretation": null,
                "status": "AMENDED",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1709751755000,
                "conceptNameToDisplay": "Intake Route",
                "valueAsString": "IV",
                "concept": {
                    "uuid": "90be572b-3309-42be-53c6-f30c03ed9f17",
                    "name": "Intake Route",
                    "dataType": "Coded",
                    "shortName": "Intake Route",
                    "units": null,
                    "conceptClass": "Question",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "conceptUuid": "90be572b-3309-42be-53c6-f30c03ed9f17",
                "voidReason": null,
                "uuid": "6b7f3943-72e4-4e5e-9ca8-49dbfd06b916",
                "voided": false,
                "comment": "route notes",
                "value": {
                    "uuid": "977628f5-5c49-0461-a128-cdcfe94fa0cc",
                    "name": "Intake Route IV",
                    "dataType": "N/A",
                    "shortName": "IV",
                    "units": null,
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                }
            },
            {
                "encounterDateTime": 1709751755000,
                "visitStartDateTime": 1709291229000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Numeric",
                "encounterUuid": "ace83e56-e4a2-4418-a337-0a837ab026c6",
                "obsGroupUuid": "e58c4f98-8c5c-4dc9-8be1-780cedf9f701",
                "creatorName": "Super Man",
                "conceptSortWeight": 3,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-0/3-0/5-0",
                "interpretation": null,
                "status": "AMENDED",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1709751755000,
                "conceptNameToDisplay": "Intake Quantity",
                "valueAsString": "180.0",
                "concept": {
                    "uuid": "65787272-0497-6457-2c43-7031ebc27f4d",
                    "name": "Intake Quantity",
                    "dataType": "Numeric",
                    "shortName": "Intake Quantity",
                    "units": "ml",
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "conceptUuid": "65787272-0497-6457-2c43-7031ebc27f4d",
                "voidReason": null,
                "uuid": "cb9649dd-a6bb-4385-82a9-88b1aa0e3022",
                "voided": false,
                "comment": "quantity notes",
                "value": 180.0
            },
            {
                "encounterDateTime": 1709751755000,
                "visitStartDateTime": 1709291229000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Datetime",
                "encounterUuid": "ace83e56-e4a2-4418-a337-0a837ab026c6",
                "obsGroupUuid": "e58c4f98-8c5c-4dc9-8be1-780cedf9f701",
                "creatorName": "Super Man",
                "conceptSortWeight": 4,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-0/3-0/6-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1709751755000,
                "conceptNameToDisplay": "Date & Time",
                "valueAsString": "2024-03-07 10:00:00",
                "concept": {
                    "uuid": "46e779c4-357f-55e5-391f-5b5d0f1b07e6",
                    "name": "Intake Date & Time",
                    "dataType": "Datetime",
                    "shortName": "Date & Time",
                    "units": null,
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "conceptUuid": "46e779c4-357f-55e5-391f-5b5d0f1b07e6",
                "voidReason": null,
                "uuid": "4d194353-4bb6-44ff-9ec2-2d6b395be946",
                "voided": false,
                "comment": null,
                "value": "2024-03-07 10:00:00"
            }
        ],
        "providers": [
            {
                "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                "name": "Super Man",
                "encounterRoleUuid": null
            }
        ],
        "isAbnormal": null,
        "duration": null,
        "type": null,
        "encounterUuid": "ace83e56-e4a2-4418-a337-0a837ab026c6",
        "obsGroupUuid": null,
        "creatorName": "Super Man",
        "conceptSortWeight": 1,
        "parentConceptUuid": null,
        "hiNormal": null,
        "lowNormal": null,
        "formNamespace": "Bahmni",
        "formFieldPath": "Intake & Output.1/11-0/3-0",
        "interpretation": null,
        "status": "FINAL",
        "encounterTypeName": "Consultation",
        "complexData": null,
        "abnormal": null,
        "unknown": false,
        "orderUuid": null,
        "observationDateTime": 1709751755000,
        "conceptNameToDisplay": "Intake",
        "valueAsString": "March 7, 2024 10:00:00 AM IST, Intake Route IV, 180.0",
        "concept": {
            "uuid": "776e8395-1f77-76fe-66ff-7211ebe58d89",
            "name": "Intake Section",
            "dataType": "N/A",
            "shortName": "Intake",
            "units": null,
            "conceptClass": "ConvSet",
            "hiNormal": null,
            "lowNormal": null,
            "set": true,
            "mappings": []
        },
        "conceptUuid": "776e8395-1f77-76fe-66ff-7211ebe58d89",
        "voidReason": null,
        "uuid": "e58c4f98-8c5c-4dc9-8be1-780cedf9f701",
        "voided": false,
        "comment": null,
        "value": "March 7, 2024 10:00:00 AM IST, Intake Route IV, 180.0"
    },
    {
        "encounterDateTime": 1709751755000,
        "visitStartDateTime": 1709291229000,
        "targetObsRelation": null,
        "groupMembers": [
            {
                "encounterDateTime": 1709751755000,
                "visitStartDateTime": 1709291229000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Coded",
                "encounterUuid": "ace83e56-e4a2-4418-a337-0a837ab026c6",
                "obsGroupUuid": "4365a317-1c5d-4d1f-a820-d8f1af2f2ede",
                "creatorName": "Super Man",
                "conceptSortWeight": 2,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-1/3-0/4-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1709751755000,
                "conceptNameToDisplay": "Intake Route",
                "valueAsString": "Oral",
                "concept": {
                    "uuid": "90be572b-3309-42be-53c6-f30c03ed9f17",
                    "name": "Intake Route",
                    "dataType": "Coded",
                    "shortName": "Intake Route",
                    "units": null,
                    "conceptClass": "Question",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "conceptUuid": "90be572b-3309-42be-53c6-f30c03ed9f17",
                "voidReason": null,
                "uuid": "659eccbb-d706-420e-927e-0af18e8e3e86",
                "voided": false,
                "comment": null,
                "value": {
                    "uuid": "c27d3789-935c-459e-5454-39c0f71a5b61",
                    "name": "Intake Route Oral",
                    "dataType": "N/A",
                    "shortName": "Oral",
                    "units": null,
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                }
            },
            {
                "encounterDateTime": 1709751755000,
                "visitStartDateTime": 1709291229000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Numeric",
                "encounterUuid": "ace83e56-e4a2-4418-a337-0a837ab026c6",
                "obsGroupUuid": "4365a317-1c5d-4d1f-a820-d8f1af2f2ede",
                "creatorName": "Super Man",
                "conceptSortWeight": 3,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-1/3-0/5-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1709751755000,
                "conceptNameToDisplay": "Intake Quantity",
                "valueAsString": "50.0",
                "concept": {
                    "uuid": "65787272-0497-6457-2c43-7031ebc27f4d",
                    "name": "Intake Quantity",
                    "dataType": "Numeric",
                    "shortName": "Intake Quantity",
                    "units": "ml",
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "conceptUuid": "65787272-0497-6457-2c43-7031ebc27f4d",
                "voidReason": null,
                "uuid": "31e6d46c-c416-423a-9300-bf8a11419cd2",
                "voided": false,
                "comment": null,
                "value": 50.0
            },
            {
                "encounterDateTime": 1709751755000,
                "visitStartDateTime": 1709291229000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Datetime",
                "encounterUuid": "ace83e56-e4a2-4418-a337-0a837ab026c6",
                "obsGroupUuid": "4365a317-1c5d-4d1f-a820-d8f1af2f2ede",
                "creatorName": "Super Man",
                "conceptSortWeight": 4,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-1/3-0/6-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1709751755000,
                "conceptNameToDisplay": "Date & Time",
                "valueAsString": "2024-03-07 12:00:00",
                "concept": {
                    "uuid": "46e779c4-357f-55e5-391f-5b5d0f1b07e6",
                    "name": "Intake Date & Time",
                    "dataType": "Datetime",
                    "shortName": "Date & Time",
                    "units": null,
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "conceptUuid": "46e779c4-357f-55e5-391f-5b5d0f1b07e6",
                "voidReason": null,
                "uuid": "227ef2f5-3fb1-44b1-9db4-864a4eb26ab8",
                "voided": false,
                "comment": null,
                "value": "2024-03-07 12:00:00"
            }
        ],
        "providers": [
            {
                "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                "name": "Super Man",
                "encounterRoleUuid": null
            }
        ],
        "isAbnormal": null,
        "duration": null,
        "type": null,
        "encounterUuid": "ace83e56-e4a2-4418-a337-0a837ab026c6",
        "obsGroupUuid": null,
        "creatorName": "Super Man",
        "conceptSortWeight": 1,
        "parentConceptUuid": null,
        "hiNormal": null,
        "lowNormal": null,
        "formNamespace": "Bahmni",
        "formFieldPath": "Intake & Output.1/11-1/3-0",
        "interpretation": null,
        "status": "FINAL",
        "encounterTypeName": "Consultation",
        "complexData": null,
        "abnormal": null,
        "unknown": false,
        "orderUuid": null,
        "observationDateTime": 1709751755000,
        "conceptNameToDisplay": "Intake",
        "valueAsString": "Intake Route Oral, 50.0, March 7, 2024 12:00:00 PM IST",
        "concept": {
            "uuid": "776e8395-1f77-76fe-66ff-7211ebe58d89",
            "name": "Intake Section",
            "dataType": "N/A",
            "shortName": "Intake",
            "units": null,
            "conceptClass": "ConvSet",
            "hiNormal": null,
            "lowNormal": null,
            "set": true,
            "mappings": []
        },
        "conceptUuid": "776e8395-1f77-76fe-66ff-7211ebe58d89",
        "voidReason": null,
        "uuid": "4365a317-1c5d-4d1f-a820-d8f1af2f2ede",
        "voided": false,
        "comment": null,
        "value": "Intake Route Oral, 50.0, March 7, 2024 12:00:00 PM IST"
    },
    {
        "encounterDateTime": 1710361652000,
        "visitStartDateTime": 1709561979000,
        "targetObsRelation": null,
        "groupMembers": [
            {
                "encounterDateTime": 1710361652000,
                "visitStartDateTime": 1709561979000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Coded",
                "encounterUuid": "2782e27e-4a85-48b7-a40a-a088a7bf07cc",
                "obsGroupUuid": "9d0ecb51-9d58-4a9f-b3cc-ec5fd33c330c",
                "creatorName": "Super Man",
                "conceptSortWeight": 2,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-0/7-0/8-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1710361653000,
                "conceptNameToDisplay": "Output Route",
                "concept": {
                    "uuid": "c6e830c6-2104-8068-3dcd-fd6ad833a5ac",
                    "name": "Output Route",
                    "dataType": "Coded",
                    "shortName": "Output Route",
                    "units": null,
                    "conceptClass": "Question",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "valueAsString": "Urine",
                "voided": false,
                "voidReason": null,
                "conceptUuid": "c6e830c6-2104-8068-3dcd-fd6ad833a5ac",
                "uuid": "4ae0ce6e-401b-4dd1-a4f6-f328ac0250d7",
                "comment": null,
                "value": {
                    "uuid": "6c204711-527c-2727-9002-5ff260a16881",
                    "name": "Output Route Urine",
                    "dataType": "N/A",
                    "shortName": "Urine",
                    "units": null,
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                }
            },
            {
                "encounterDateTime": 1710361652000,
                "visitStartDateTime": 1709561979000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Numeric",
                "encounterUuid": "2782e27e-4a85-48b7-a40a-a088a7bf07cc",
                "obsGroupUuid": "9d0ecb51-9d58-4a9f-b3cc-ec5fd33c330c",
                "creatorName": "Super Man",
                "conceptSortWeight": 3,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-0/7-0/9-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1710361653000,
                "conceptNameToDisplay": "Output Quantity",
                "concept": {
                    "uuid": "0656118f-8c8e-3bd9-6554-619e5c678a4b",
                    "name": "Output Quantity",
                    "dataType": "Numeric",
                    "shortName": "Output Quantity",
                    "units": "ml",
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "valueAsString": "10.0",
                "voided": false,
                "voidReason": null,
                "conceptUuid": "0656118f-8c8e-3bd9-6554-619e5c678a4b",
                "uuid": "9c659ee7-f497-429e-b6c6-65bac4bad1d3",
                "comment": null,
                "value": 10.0
            },
            {
                "encounterDateTime": 1710361652000,
                "visitStartDateTime": 1709561979000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Datetime",
                "encounterUuid": "2782e27e-4a85-48b7-a40a-a088a7bf07cc",
                "obsGroupUuid": "9d0ecb51-9d58-4a9f-b3cc-ec5fd33c330c",
                "creatorName": "Super Man",
                "conceptSortWeight": 4,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-0/7-0/10-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1710361653000,
                "conceptNameToDisplay": "Date & Time",
                "concept": {
                    "uuid": "8a81f755-4993-25f0-3490-963787e98dbf",
                    "name": "Output Date & Time",
                    "dataType": "Datetime",
                    "shortName": "Date & Time",
                    "units": null,
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "valueAsString": "2024-03-07 16:00:00",
                "voided": false,
                "voidReason": null,
                "conceptUuid": "8a81f755-4993-25f0-3490-963787e98dbf",
                "uuid": "fd7dfe2f-59be-40d0-90fa-77021a3350b9",
                "comment": null,
                "value": "2024-03-07 16:00:00"
            }
        ],
        "providers": [
            {
                "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                "name": "Super Man",
                "encounterRoleUuid": null
            }
        ],
        "isAbnormal": null,
        "duration": null,
        "type": null,
        "encounterUuid": "2782e27e-4a85-48b7-a40a-a088a7bf07cc",
        "obsGroupUuid": null,
        "creatorName": "Super Man",
        "conceptSortWeight": 5,
        "parentConceptUuid": null,
        "hiNormal": null,
        "lowNormal": null,
        "formNamespace": "Bahmni",
        "formFieldPath": "Intake & Output.1/11-0/7-0",
        "interpretation": null,
        "status": "FINAL",
        "encounterTypeName": "Consultation",
        "complexData": null,
        "abnormal": null,
        "unknown": false,
        "orderUuid": null,
        "observationDateTime": 1710361653000,
        "conceptNameToDisplay": "Output",
        "concept": {
            "uuid": "c090ae63-6b65-4958-9c74-77e3bf118206",
            "name": "Output Section",
            "dataType": "N/A",
            "shortName": "Output",
            "units": null,
            "conceptClass": "ConvSet",
            "hiNormal": null,
            "lowNormal": null,
            "set": true,
            "mappings": []
        },
        "valueAsString": "10.0, March 7, 2024 4:00:00 PM IST, Output Route Urine",
        "voided": false,
        "voidReason": null,
        "conceptUuid": "c090ae63-6b65-4958-9c74-77e3bf118206",
        "uuid": "9d0ecb51-9d58-4a9f-b3cc-ec5fd33c330c",
        "comment": null,
        "value": "10.0, March 7, 2024 4:00:00 PM IST, Output Route Urine"
    },
    {
        "encounterDateTime": 1710361652000,
        "visitStartDateTime": 1709561979000,
        "targetObsRelation": null,
        "groupMembers": [
            {
                "encounterDateTime": 1710361652000,
                "visitStartDateTime": 1709561979000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Coded",
                "encounterUuid": "2782e27e-4a85-48b7-a40a-a088a7bf07cc",
                "obsGroupUuid": "fc0ac1e7-a2bd-4e42-83db-60938d06c4e5",
                "creatorName": "Super Man",
                "conceptSortWeight": 2,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-0/3-0/4-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1710361653000,
                "conceptNameToDisplay": "Intake Route",
                "concept": {
                    "uuid": "90be572b-3309-42be-53c6-f30c03ed9f17",
                    "name": "Intake Route",
                    "dataType": "Coded",
                    "shortName": "Intake Route",
                    "units": null,
                    "conceptClass": "Question",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "valueAsString": "Oral",
                "voided": false,
                "voidReason": null,
                "conceptUuid": "90be572b-3309-42be-53c6-f30c03ed9f17",
                "uuid": "9685939a-8efc-4ad8-b894-b24532a49fd3",
                "comment": null,
                "value": {
                    "uuid": "c27d3789-935c-459e-5454-39c0f71a5b61",
                    "name": "Intake Route Oral",
                    "dataType": "N/A",
                    "shortName": "Oral",
                    "units": null,
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                }
            },
            {
                "encounterDateTime": 1710361652000,
                "visitStartDateTime": 1709561979000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Numeric",
                "encounterUuid": "2782e27e-4a85-48b7-a40a-a088a7bf07cc",
                "obsGroupUuid": "fc0ac1e7-a2bd-4e42-83db-60938d06c4e5",
                "creatorName": "Super Man",
                "conceptSortWeight": 3,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-0/3-0/5-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1710361653000,
                "conceptNameToDisplay": "Intake Quantity",
                "concept": {
                    "uuid": "65787272-0497-6457-2c43-7031ebc27f4d",
                    "name": "Intake Quantity",
                    "dataType": "Numeric",
                    "shortName": "Intake Quantity",
                    "units": "ml",
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "valueAsString": "30.0",
                "voided": false,
                "voidReason": null,
                "conceptUuid": "65787272-0497-6457-2c43-7031ebc27f4d",
                "uuid": "65912c35-4a77-4b96-a8ea-07e5edf2e5f8",
                "comment": null,
                "value": 30.0
            },
            {
                "encounterDateTime": 1710361652000,
                "visitStartDateTime": 1709561979000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Datetime",
                "encounterUuid": "2782e27e-4a85-48b7-a40a-a088a7bf07cc",
                "obsGroupUuid": "fc0ac1e7-a2bd-4e42-83db-60938d06c4e5",
                "creatorName": "Super Man",
                "conceptSortWeight": 4,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-0/3-0/6-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1710361653000,
                "conceptNameToDisplay": "Date & Time",
                "concept": {
                    "uuid": "46e779c4-357f-55e5-391f-5b5d0f1b07e6",
                    "name": "Intake Date & Time",
                    "dataType": "Datetime",
                    "shortName": "Date & Time",
                    "units": null,
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "valueAsString": "2024-03-07 15:00:00",
                "voided": false,
                "voidReason": null,
                "conceptUuid": "46e779c4-357f-55e5-391f-5b5d0f1b07e6",
                "uuid": "14e9736a-b33a-48aa-a07d-996ca6139c24",
                "comment": null,
                "value": "2024-03-07 15:00:00"
            }
        ],
        "providers": [
            {
                "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                "name": "Super Man",
                "encounterRoleUuid": null
            }
        ],
        "isAbnormal": null,
        "duration": null,
        "type": null,
        "encounterUuid": "2782e27e-4a85-48b7-a40a-a088a7bf07cc",
        "obsGroupUuid": null,
        "creatorName": "Super Man",
        "conceptSortWeight": 1,
        "parentConceptUuid": null,
        "hiNormal": null,
        "lowNormal": null,
        "formNamespace": "Bahmni",
        "formFieldPath": "Intake & Output.1/11-0/3-0",
        "interpretation": null,
        "status": "FINAL",
        "encounterTypeName": "Consultation",
        "complexData": null,
        "abnormal": null,
        "unknown": false,
        "orderUuid": null,
        "observationDateTime": 1710361653000,
        "conceptNameToDisplay": "Intake",
        "concept": {
            "uuid": "776e8395-1f77-76fe-66ff-7211ebe58d89",
            "name": "Intake Section",
            "dataType": "N/A",
            "shortName": "Intake",
            "units": null,
            "conceptClass": "ConvSet",
            "hiNormal": null,
            "lowNormal": null,
            "set": true,
            "mappings": []
        },
        "valueAsString": "30.0, March 7, 2024 3:00:00 PM IST, Intake Route Oral",
        "voided": false,
        "voidReason": null,
        "conceptUuid": "776e8395-1f77-76fe-66ff-7211ebe58d89",
        "uuid": "fc0ac1e7-a2bd-4e42-83db-60938d06c4e5",
        "comment": null,
        "value": "30.0, March 7, 2024 3:00:00 PM IST, Intake Route Oral"
    },
    {
        "encounterDateTime": 1710361652000,
        "visitStartDateTime": 1709561979000,
        "targetObsRelation": null,
        "groupMembers": [
            {
                "encounterDateTime": 1710361652000,
                "visitStartDateTime": 1709561979000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Coded",
                "encounterUuid": "2782e27e-4a85-48b7-a40a-a088a7bf07cc",
                "obsGroupUuid": "598411e5-434b-4234-a153-f312ba554847",
                "creatorName": "Super Man",
                "conceptSortWeight": 2,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-1/3-0/4-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1710361653000,
                "conceptNameToDisplay": "Intake Route",
                "concept": {
                    "uuid": "90be572b-3309-42be-53c6-f30c03ed9f17",
                    "name": "Intake Route",
                    "dataType": "Coded",
                    "shortName": "Intake Route",
                    "units": null,
                    "conceptClass": "Question",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "valueAsString": "NG Tube Feeds",
                "voided": false,
                "voidReason": null,
                "conceptUuid": "90be572b-3309-42be-53c6-f30c03ed9f17",
                "uuid": "cab78ee5-85ee-4646-8687-5efdf658a819",
                "comment": null,
                "value": {
                    "uuid": "5fac6eaf-94e9-78e8-2ba9-ac8385ef5e45",
                    "name": "Intake Route NG Tube Feeds",
                    "dataType": "N/A",
                    "shortName": "NG Tube Feeds",
                    "units": null,
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                }
            },
            {
                "encounterDateTime": 1710361652000,
                "visitStartDateTime": 1709561979000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Numeric",
                "encounterUuid": "2782e27e-4a85-48b7-a40a-a088a7bf07cc",
                "obsGroupUuid": "598411e5-434b-4234-a153-f312ba554847",
                "creatorName": "Super Man",
                "conceptSortWeight": 3,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-1/3-0/5-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1710361653000,
                "conceptNameToDisplay": "Intake Quantity",
                "concept": {
                    "uuid": "65787272-0497-6457-2c43-7031ebc27f4d",
                    "name": "Intake Quantity",
                    "dataType": "Numeric",
                    "shortName": "Intake Quantity",
                    "units": "ml",
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "valueAsString": "100.0",
                "voided": false,
                "voidReason": null,
                "conceptUuid": "65787272-0497-6457-2c43-7031ebc27f4d",
                "uuid": "318c8730-2f99-4d88-b3fe-2b2501d9a1fb",
                "comment": null,
                "value": 100.0
            },
            {
                "encounterDateTime": 1710361652000,
                "visitStartDateTime": 1709561979000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Datetime",
                "encounterUuid": "2782e27e-4a85-48b7-a40a-a088a7bf07cc",
                "obsGroupUuid": "598411e5-434b-4234-a153-f312ba554847",
                "creatorName": "Super Man",
                "conceptSortWeight": 4,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-1/3-0/6-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1710361653000,
                "conceptNameToDisplay": "Date & Time",
                "concept": {
                    "uuid": "46e779c4-357f-55e5-391f-5b5d0f1b07e6",
                    "name": "Intake Date & Time",
                    "dataType": "Datetime",
                    "shortName": "Date & Time",
                    "units": null,
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "valueAsString": "2024-03-08 13:00:00",
                "voided": false,
                "voidReason": null,
                "conceptUuid": "46e779c4-357f-55e5-391f-5b5d0f1b07e6",
                "uuid": "39bf3c34-356f-4de6-9dd2-68240526254b",
                "comment": null,
                "value": "2024-03-08 13:00:00"
            }
        ],
        "providers": [
            {
                "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                "name": "Super Man",
                "encounterRoleUuid": null
            }
        ],
        "isAbnormal": null,
        "duration": null,
        "type": null,
        "encounterUuid": "2782e27e-4a85-48b7-a40a-a088a7bf07cc",
        "obsGroupUuid": null,
        "creatorName": "Super Man",
        "conceptSortWeight": 1,
        "parentConceptUuid": null,
        "hiNormal": null,
        "lowNormal": null,
        "formNamespace": "Bahmni",
        "formFieldPath": "Intake & Output.1/11-1/3-0",
        "interpretation": null,
        "status": "FINAL",
        "encounterTypeName": "Consultation",
        "complexData": null,
        "abnormal": null,
        "unknown": false,
        "orderUuid": null,
        "observationDateTime": 1710361653000,
        "conceptNameToDisplay": "Intake",
        "concept": {
            "uuid": "776e8395-1f77-76fe-66ff-7211ebe58d89",
            "name": "Intake Section",
            "dataType": "N/A",
            "shortName": "Intake",
            "units": null,
            "conceptClass": "ConvSet",
            "hiNormal": null,
            "lowNormal": null,
            "set": true,
            "mappings": []
        },
        "valueAsString": "March 8, 2024 1:00:00 PM IST, Intake Route NG Tube Feeds, 100.0",
        "voided": false,
        "voidReason": null,
        "conceptUuid": "776e8395-1f77-76fe-66ff-7211ebe58d89",
        "uuid": "598411e5-434b-4234-a153-f312ba554847",
        "comment": null,
        "value": "March 8, 2024 1:00:00 PM IST, Intake Route NG Tube Feeds, 100.0"
    },
    {
        "encounterDateTime": 1710361652000,
        "visitStartDateTime": 1709561979000,
        "targetObsRelation": null,
        "groupMembers": [
            {
                "encounterDateTime": 1710361652000,
                "visitStartDateTime": 1709561979000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Coded",
                "encounterUuid": "2782e27e-4a85-48b7-a40a-a088a7bf07cc",
                "obsGroupUuid": "c2fa2d2c-23f2-4686-8341-9724e06e1689",
                "creatorName": "Super Man",
                "conceptSortWeight": 2,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-1/7-0/8-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1710361653000,
                "conceptNameToDisplay": "Output Route",
                "concept": {
                    "uuid": "c6e830c6-2104-8068-3dcd-fd6ad833a5ac",
                    "name": "Output Route",
                    "dataType": "Coded",
                    "shortName": "Output Route",
                    "units": null,
                    "conceptClass": "Question",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "valueAsString": "Other",
                "voided": false,
                "voidReason": null,
                "conceptUuid": "c6e830c6-2104-8068-3dcd-fd6ad833a5ac",
                "uuid": "09285dc5-e82b-42b5-aa94-0a2c9b56fffb",
                "comment": null,
                "value": {
                    "uuid": "16ab8f3a-9bbe-8bff-7351-b5b1de4b3e23",
                    "name": "Output Route Other",
                    "dataType": "N/A",
                    "shortName": "Other",
                    "units": null,
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                }
            },
            {
                "encounterDateTime": 1710361652000,
                "visitStartDateTime": 1709561979000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Numeric",
                "encounterUuid": "2782e27e-4a85-48b7-a40a-a088a7bf07cc",
                "obsGroupUuid": "c2fa2d2c-23f2-4686-8341-9724e06e1689",
                "creatorName": "Super Man",
                "conceptSortWeight": 3,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-1/7-0/9-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1710361653000,
                "conceptNameToDisplay": "Output Quantity",
                "concept": {
                    "uuid": "0656118f-8c8e-3bd9-6554-619e5c678a4b",
                    "name": "Output Quantity",
                    "dataType": "Numeric",
                    "shortName": "Output Quantity",
                    "units": "ml",
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "valueAsString": "70.0",
                "voided": false,
                "voidReason": null,
                "conceptUuid": "0656118f-8c8e-3bd9-6554-619e5c678a4b",
                "uuid": "22aa3530-92d3-4b44-8a58-2c8887f124a0",
                "comment": null,
                "value": 70.0
            },
            {
                "encounterDateTime": 1710361652000,
                "visitStartDateTime": 1709561979000,
                "targetObsRelation": null,
                "groupMembers": [],
                "providers": [
                    {
                        "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                        "name": "Super Man",
                        "encounterRoleUuid": null
                    }
                ],
                "isAbnormal": null,
                "duration": null,
                "type": "Datetime",
                "encounterUuid": "2782e27e-4a85-48b7-a40a-a088a7bf07cc",
                "obsGroupUuid": "c2fa2d2c-23f2-4686-8341-9724e06e1689",
                "creatorName": "Super Man",
                "conceptSortWeight": 4,
                "parentConceptUuid": null,
                "hiNormal": null,
                "lowNormal": null,
                "formNamespace": "Bahmni",
                "formFieldPath": "Intake & Output.1/11-1/7-0/10-0",
                "interpretation": null,
                "status": "FINAL",
                "encounterTypeName": "Consultation",
                "complexData": null,
                "abnormal": null,
                "unknown": false,
                "orderUuid": null,
                "observationDateTime": 1710361653000,
                "conceptNameToDisplay": "Date & Time",
                "concept": {
                    "uuid": "8a81f755-4993-25f0-3490-963787e98dbf",
                    "name": "Output Date & Time",
                    "dataType": "Datetime",
                    "shortName": "Date & Time",
                    "units": null,
                    "conceptClass": "Misc",
                    "hiNormal": null,
                    "lowNormal": null,
                    "set": false,
                    "mappings": []
                },
                "valueAsString": "2024-03-08 15:00:00",
                "voided": false,
                "voidReason": null,
                "conceptUuid": "8a81f755-4993-25f0-3490-963787e98dbf",
                "uuid": "f7a8464d-e0e0-4a3b-bc9f-d8dd9a553fe3",
                "comment": null,
                "value": "2024-03-08 15:00:00"
            }
        ],
        "providers": [
            {
                "uuid": "c1c26908-3f10-11e4-adec-0800271c1b75",
                "name": "Super Man",
                "encounterRoleUuid": null
            }
        ],
        "isAbnormal": null,
        "duration": null,
        "type": null,
        "encounterUuid": "2782e27e-4a85-48b7-a40a-a088a7bf07cc",
        "obsGroupUuid": null,
        "creatorName": "Super Man",
        "conceptSortWeight": 5,
        "parentConceptUuid": null,
        "hiNormal": null,
        "lowNormal": null,
        "formNamespace": "Bahmni",
        "formFieldPath": "Intake & Output.1/11-1/7-0",
        "interpretation": null,
        "status": "FINAL",
        "encounterTypeName": "Consultation",
        "complexData": null,
        "abnormal": null,
        "unknown": false,
        "orderUuid": null,
        "observationDateTime": 1710361653000,
        "conceptNameToDisplay": "Output",
        "concept": {
            "uuid": "c090ae63-6b65-4958-9c74-77e3bf118206",
            "name": "Output Section",
            "dataType": "N/A",
            "shortName": "Output",
            "units": null,
            "conceptClass": "ConvSet",
            "hiNormal": null,
            "lowNormal": null,
            "set": true,
            "mappings": []
        },
        "valueAsString": "70.0, March 8, 2024 3:00:00 PM IST, Output Route Other",
        "voided": false,
        "voidReason": null,
        "conceptUuid": "c090ae63-6b65-4958-9c74-77e3bf118206",
        "uuid": "c2fa2d2c-23f2-4686-8341-9724e06e1689",
        "comment": null,
        "value": "70.0, March 8, 2024 3:00:00 PM IST, Output Route Other"
    }
];