export const mockWardList = [
  {
    ward: {
      uuid: "baf7bd38-d225-11e4-9c67-080027b662ec",
      display: "General Ward",
      name: "General Ward",
      description: null,
      address1: null,
      address2: "Admission Location",
      retired: false,
      attributes: [],
      address7: null,
      address8: null,
      address9: null,
      address10: null,
      address11: null,
      address12: null,
      address13: null,
      address14: null,
      address15: null,
      resourceVersion: "2.0",
    },
    totalBeds: 40,
    occupiedBeds: 27,
  },
];
