export const drugChartData = [
  [
    {
      8: {
        minutes: 0,
        status: "SCHEDULED",
      },
      13: {
        minutes: 0,
        status: "SCHEDULED",
      },
      17: {
        minutes: 0,
        status: "SCHEDULED",
      },
      23: {
        minutes: 55,
        status: "SCHEDULED",
      },
    },
    {
      11: {
        minutes: 0,
        status: "SCHEDULED",
      },
      15: {
        minutes: 55,
        status: "SCHEDULED",
      },
      19: {
        minutes: 10,
        status: "SCHEDULED",
      },
    },
  ],
  [
    {
      drugName: "Suxamethonium Chloride 100 mg/2 mL Ampoule (50 mg/mL )",
      drugRoute: "Intravenous",
      administrationInfo: [],
      duration: "4 Day(s)",
      dosage: 2,
      doseType: "mg",
      dosingInstructions:
        '{"instructions":"Before meals","additionalInstructions":"sample additional instruction"}',
    },
    {
      drugName: "Enalapril 5 mg Tablet",
      drugRoute: "Oral",
      administrationInfo: [],
      duration: "4 Day(s)",
      dosage: 1,
      doseType: "Tablet(s)",
      dosingInstructions:
        '{"instructions":"Before meals","additionalInstructions":"sample additional instruction"}',
    },
  ],
];

export const mockDrugChartDataLarge = [
  {
    uuid: "ca1e7546-24b9-4c2e-9ffb-5365b71ae4f4",
    name: "Amoxicillin/Clavulanic Acid  125 mg/31.25 mg/5 mL Powder for Oral Suspension",
    dosingInstructions: {
      route: "Topical",
      dosage: "1mg",
      asNeeded: false,
      frequency: "Twice a day",
      instructions: {
        instructions: "As directed",
      },
    },
    duration: "2 Day(s)",
    slots: [],
    dateStopped: null,
    orderReasonText: null,
    firstSlotStartTime: 1707396840,
    notes: "",
  },
  {
    uuid: "347b0c8e-2c29-46a4-a07f-bdc73fada7ea",
    name: "Amoxicillin/Clavulanic Acid  400 mg/57 mg/5 mL Powder for Oral Suspension",
    dosingInstructions: {
      route: "Topical",
      dosage: "2mg",
      asNeeded: false,
      frequency: "Twice a day",
      instructions: {
        instructions: "As directed",
      },
    },
    duration: "2 Day(s)",
    slots: [],
    dateStopped: null,
    orderReasonText: null,
    firstSlotStartTime: 1707396900,
    notes: "",
  },
  {
    uuid: "23f34c32-79f9-4c89-87de-16b5da662120",
    name: "Amoxicillin/Clavulanic Acid 1000 mg Tablet",
    dosingInstructions: {
      route: "Oral",
      dosage: 1,
      doseUnits: "Tablet(s)",
      asNeeded: false,
      frequency: "Twice a day",
      instructions: {
        instructions: "As directed",
      },
    },
    duration: "2 Day(s)",
    slots: [],
    dateStopped: null,
    orderReasonText: null,
    firstSlotStartTime: 1707396900,
    notes: "",
  },
  {
    uuid: "a3e0fd1b-f484-4db9-a05f-6ce97dfb3e85",
    name: "Amoxicillin/Clavulanic Acid  250 mg/62.5 mg/5 mL Powder for Oral Suspension",
    dosingInstructions: {
      route: "Topical",
      dosage: "2mg",
      asNeeded: false,
      frequency: "Twice a day",
      instructions: {
        instructions: "As directed",
      },
    },
    duration: "2 Day(s)",
    slots: [],
    dateStopped: null,
    orderReasonText: null,
    firstSlotStartTime: 1707396900,
    notes: "",
  },
  {
    uuid: "9ada7a29-edc0-4801-ac84-e16d8d1a10ec",
    name: "Adrenaline 1 mg/mL (1 mL) Ampoule",
    dosingInstructions: {
      route: "Intravenous",
      dosage: "2mg",
      asNeeded: false,
      frequency: "Twice a day",
      instructions: {
        instructions: "As directed",
      },
    },
    duration: "2 Day(s)",
    slots: [],
    dateStopped: null,
    orderReasonText: null,
    firstSlotStartTime: 1707396900,
    notes: "",
  },
  {
    uuid: "bf19b2d3-1148-43b9-b3a2-8b0b2bd892aa",
    name: "Paracetamol 120 mg/5 mL Suspension",
    dosingInstructions: {
      route: "Oral",
      dosage: "2ml",
      asNeeded: false,
      frequency: "Twice a day",
      instructions: {
        instructions: "As directed",
      },
    },
    duration: "2 Day(s)",
    slots: [],
    dateStopped: null,
    orderReasonText: null,
    firstSlotStartTime: 1707396900,
    notes: "",
  },
  {
    uuid: "ffa1e186-2c18-4909-b553-54516fa1440b",
    name: "Paracetamol 125 mg Suppository",
    dosingInstructions: {
      route: "Oral",
      dosage: 2,
      doseUnits: "Tablet(s)",
      asNeeded: false,
      frequency: "Twice a day",
      instructions: {
        instructions: "As directed",
      },
    },
    duration: "2 Day(s)",
    slots: [],
    dateStopped: null,
    orderReasonText: null,
    firstSlotStartTime: 1707396900,
    notes: "",
  },
  {
    uuid: "4d1053c0-13ae-40ff-a2da-60043c72b89f",
    name: "Paracetamol 250 mg Suppository",
    dosingInstructions: {
      route: "Oral",
      dosage: 2,
      doseUnits: "Tablet(s)",
      asNeeded: false,
      frequency: "Twice a day",
      instructions: {
        instructions: "As directed",
      },
    },
    duration: "2 Day(s)",
    slots: [],
    dateStopped: null,
    orderReasonText: null,
    firstSlotStartTime: 1707396900,
    notes: "",
  },
  {
    uuid: "886821bc-fedf-4af8-a7a3-020df006db8f",
    name: "Paracetamol 500 mg Tablet",
    dosingInstructions: {
      route: "Oral",
      dosage: 2,
      doseUnits: "Tablet(s)",
      asNeeded: false,
      frequency: "Twice a day",
      instructions: {
        instructions: "As directed",
      },
    },
    duration: "2 Day(s)",
    slots: [],
    dateStopped: null,
    orderReasonText: null,
    firstSlotStartTime: 1707396900,
    notes: "",
  },
  {
    uuid: "452dc2ca-a875-4e9c-a6fa-626b99a892c5",
    name: "Isoflurane 250 mL Inhalation Anesthetic Liquid",
    dosingInstructions: {
      route: "Oral",
      dosage: "2ml",
      asNeeded: false,
      frequency: "Twice a day",
      instructions: {
        instructions: "As directed",
      },
    },
    duration: "2 Day(s)",
    slots: [],
    dateStopped: null,
    orderReasonText: null,
    firstSlotStartTime: 1707396900,
    notes: "",
  },
  {
    uuid: "e5eee2bd-5348-4dbb-b113-598ff2ba76a3",
    name: "Cimetidine 200 mg/2 mL Ampoule",
    dosingInstructions: {
      route: "Intravenous",
      dosage: "2mg",
      asNeeded: false,
      frequency: "Twice a day",
      instructions: {
        instructions: "As directed",
      },
    },
    duration: "2 Day(s)",
    slots: [],
    dateStopped: null,
    orderReasonText: null,
    firstSlotStartTime: 1707396900,
    notes: "",
  },
  {
    uuid: "840d086e-e429-4a2e-a382-f9c12bc25ebb",
    name: "Ciprofloxacin 500 mg Tablet",
    dosingInstructions: {
      route: "Oral",
      dosage: 1,
      doseUnits: "Tablet(s)",
      asNeeded: false,
      frequency: "Twice a day",
      instructions: {
        instructions: "As directed",
      },
    },
    duration: "2 Day(s)",
    slots: [],
    dateStopped: null,
    orderReasonText: null,
    firstSlotStartTime: 1707396900,
    notes: "",
  },
  {
    uuid: "e9a4c314-4f57-466f-ad15-0bdc2f8ea184",
    name: "Ciprofloxacin 0.3% Ophthalmic Ointment w/w",
    dosingInstructions: {
      route: "Topical",
      dosage: 2,
      doseUnits: "Tablet(s)",
      asNeeded: false,
      frequency: "Twice a day",
      instructions: {
        instructions: "As directed",
      },
    },
    duration: "2 Day(s)",
    slots: [],
    dateStopped: null,
    orderReasonText: null,
    firstSlotStartTime: 1707396900,
    notes: "",
  },
  {
    uuid: "d19390de-0a43-4d95-a703-d1c914936ac3",
    name: "Protein Powder",
    dosingInstructions: {
      route: "Oral",
      dosage: 1,
      doseUnits: "Unit(s)",
      asNeeded: false,
      frequency: "Twice a day",
      instructions: {
        instructions: "As directed",
      },
    },
    duration: "1 Day(s)",
    slots: [],
    dateStopped: null,
    orderReasonText: null,
    firstSlotStartTime: 1707396960,
    notes: "",
  },
  {
    uuid: "a45c4217-b2b8-4812-96bd-3db7d29382c1",
    name: "Liquid Paraffin",
    dosingInstructions: {
      route: "Topical",
      dosage: 2,
      doseUnits: "Drop",
      asNeeded: false,
      frequency: "Twice a day",
      instructions: {
        instructions: "As directed",
      },
    },
    duration: "2 Day(s)",
    slots: [],
    dateStopped: null,
    orderReasonText: null,
    firstSlotStartTime: 1707396960,
    notes: "",
  },
];
